export default [
  {
    StudentName: 'Pal',
    CollegeId: 919471,
    EmailId: 'pal626@gmail.com',
    PhoneNo: '9849923235',
    FeeStatus: 'true',
    CGPA: '9',
    English: '87',
    Science: '59',
    Maths: '70',
    History: '78',
    French: '83',
    TotalNoOfSubjects: '5',
    cricket: '60',
    kabadi: '30',
    badminton: '10',
    basketball: '0',
    hockey: '0',
    img: 'https://avatars.githubusercontent.com/u/1?v=4',
    classStrength: '40',
    class: '2nd',
    NoOfSports: '3',
    bio: "I'm on the sustainability team at Cricket, and prior to that co-founded Entelo Club",
    Overall_Attendence_percentage: '85',
    AJanFebMarch: '90',
    AAprMayJun: '80',
    AJulyAugSept: '90',
    AOctNov: '80',
    ADec: '90',
    Notification1: 'Take immediate action to protect children from Covid',
    Notification2: 'You have Half yearly Exam on 06-02-2021',
    Notification3: 'Your Quaterly results will be released on 05-02-2021',
    Notification4: 'Study Well !!!',
    Notification5: 'You have Holidays on Every Second Saturday',
  },
];
